### ISSUE TITLE
Hello, help!!

### ISSUE THREAD

**Issue by lgcambero** [FabioBaroni/WAS#1]
![1](https://cloud.githubusercontent.com/assets/11602705/18616997/14a3f522-7d9d-11e6-850f-a53f0fa935a9.png)

I'm using:

Windows 10 Pro 64bits
python-3.6.0b1
pyglet-1.2.4-PY2-none-any

You could share a more detailed instructions on installing and commissioning?.

Thank you.

**Comment by FabioBaroni** [comment]
Hello lgcambero,
since this isn't an issue of the program, but maybe you didn't figure out how to get the program running, you could have contacted me by email instead of opening an issue, but thanks for writing me anyway. I appreciate that and it can be useful for others as well. I'll close the issue once you'll be able to run the program.

I think the documentation is clear, though it doesn't contain a complete step by step description.
I see you installed python 3.6 which is a beta version, I recommend you to use a stable version. The latest stable version is 3.5.2 (anyway this shouldn't be the issue).

Then you need to install pywin32 package. If you use Python 3.5.2 this is the installation file you need: https://sourceforge.net/projects/pywin32/files/pywin32/Build%20220/pywin32-220.win-amd64-py3.5.exe/download . Just run the .exe file and you are done.

For pyglet instead there isn't a .exe file to run, but a package on https://pypi.python.org/pypi/pyglet/1.2.4
You can use pip to install from the source file or from the wheel file.
Maybe you downloaded the wrong wheel file: pyglet-1.2.4-py2-none-any.whl
See "py2"? That is compatible with python 2 but we are using python 3.x
So you should try with: pyglet-1.2.4-py3-none-any.whl

An easier way is letting pip do all the job for you (searching, downloading and installing) the right package compatible with your system architecture, operating system and python version.

You can simply issue the command: `pip install pyglet`

Note: if you see your Script directory, you find pip and pip3. pip is used to download packages for python2, instead pip3 is used for python3. If python 3 is the default on your system, then also pip will work, else you have to use pip3 to make it explicit.

You also need avbin, you can download it from here: https://github.com/downloads/AVbin/AVbin/AVbin10-win64.exe

Windows doesn't set automatically the system path for you so it can be tiring to cd into the python directory every time. It would be easier if you can just type `python` whenever you are. You can fix that by adding python and the Script directory to the system variables manually. See here: http://superuser.com/questions/949560/how-do-i-set-system-environment-variables-in-windows-10

You can also open a Powershell window and use a command similar to this:

`[Environment]::SetEnvironmentVariable("Path", "$env:Path;C:\Python27\;C:\Python27\Scripts\", "User")`

In the example, the python interpreter is located in C:\Python27\ and the Python modules directory in C:\Python27\Scripts\ . You'll have to change these 2 directories using the paths that you have on your computer.

Let me know if you could solve the problem and I'll close the issue.

Best regards,
Fabio
